### ISSUE TITLE
Create one uboot for all aries phones

### ISSUE THREAD

**Issue by PabloPL** [xc-racer99/u-boot-aries#1]
Usefull informations:
https://github.com/u-boot/u-boot/blob/master/doc/README.multi-dtb-fit
https://github.com/fourkbomb/u-boot/commit/9f123102c75fa1086d9526243889a1d4726e57dd
- board detection can be done by checking board_rev
- add s5pv210.dtsi like file for uboot, so all phones could include it (like it's done in linux kernel)

In this way we'll have one uboot board (aries maybe), which will decide which dtb file to load.

**Comment by xc-racer99** [comment]
Alright, I have a prototype common aries board at https://github.com/xc-racer99/u-boot-galaxys4g/tree/v2018.05-aries  However, I have yet to implement the actual board detection as I'm not sure if board_rev is the best way to go about it.  There's 2 issues with it that come to mind: 1) It's too early for board_rev to have been set already and 2) I'm not sure if it's the best way to go about it as looking at some i9000B they have HWREV set to 0xf which is the same as my variant.

I was thinking of comparing initial values of GPIOs to determine which board is in use.  If you wouldn't mind posting the output of gpio status -a so I can compare with values for my variant which I've uploaded to https://gist.github.com/xc-racer99/36ee444d8f672f0103b84d8ebab71f42  I'm thinking that gpd12 and/or gpd13 are the best bets as they are used for FM radio on the i9000 but nothing on my variant.

**Comment by PabloPL** [comment]
@xc-racer99 Ok, i'll do it later and post result. This could work, but only for case, when we flash uboot as SBL. It won't work if we try to flash it instead of bootloaders :/.

Edit 1:
Here is output of gpio status https://gist.github.com/PabloPL/e2828f2aeb28a9c65158a69290fa931b.

**Comment by xc-racer99** [comment]
Differences:
GPB(4) - defined as GPIO_BOOT_MODE
GPD0(0) - PWM out
GPD1(2) and GPD1(3) - FM radio related (candidate for comparison)
GPG* - MMC related
GPJ0(2) - HWREV
GPJ2(7) - MMC related
MP01(5) - defined as GPIO_DIC_ID (digital input channel?  not used in stock kernel)
GPH0(6) - defined as GPIO_DET_35 - related to jack detection
GPH3(3) - related to low battery IRQ
GPH3(5) - magnetic sensor IRQ
GPH3(7) - related to CP on i9000, unused on T959P

There's not as many differences as I'd hoped - there's two that have potential, the FM radio and the MMC card.

Finally, the other option is to mount the EFS partition on the onenand and inspect it. On my variant, the model number is present in root/afs/settings/acoustic/wbxml_version.txt and root/sys/gdfs_version.txt but my variant has an entirely different EFS structure from other first-gen devices.

**Comment by xc-racer99** [comment]
Alright, https://github.com/xc-racer99/u-boot-galaxys4g/commit/7c7f08b3758828f944e4864405bf1249ce2700a1 implements board detection.  Could you please test on an i9000 and make sure I did it correctly?

**Comment by PabloPL** [comment]
After building and flashing i got
```
Model: Samsung Galaxy S based on S5PC110
```
So it looks like it detected my device correctly.
Great!.

Now the only thing it's missing for me is having lcd driver and display menu (where we could select using buttons, what to boot).

**Comment by xc-racer99** [comment]
Great!  Will close this issue as fixed in 7c7f08b3758828f944e4864405bf1249ce2700a1

For the LCD driver, it looks as if the display menu in board/samsung/common/misc.c is entirely broken, I can't even get it to compile and the only devices that used it (trats, trats2, universal c210) no longer do.  Is there another one somewhere or should I work on forward-porting it to the new device model?

I have some untested LCD patches, I've uploaded them to https://github.com/xc-racer99/u-boot-galaxys4g/commits/s6e63m0

**Comment by PabloPL** [comment]
Hm...to get lcd working in kernel we had to "just" enable FIMD (even without lcd driver), so maybe this is first step to get it working. Also we need to mainline lcd driver in kernel.
