### ISSUE TITLE
Improved bootmenu

### ISSUE THREAD

**Issue by xc-racer99** [xc-racer99/u-boot-aries#22]
Now that I'm booting fairly often into Linux from my device, I've found it fairly clunky to keep having to go down and select the correct boot device.

As an alternative, I was considering about remembering the last used boot device and defaulting to it.  bootmenu would only show when volume up was pressed, recovery would show when volume down was pushed.  The two onenand paths could be combined with the main onenand booting when on a normal bootup with OneNAND; recovery showing if volume down was pushed or if special value was in INFORM register from reboot recovery in Android (essentially matching the stock bootloader behaviour).

The downside to this is that in order to save the most recently used bootpath; we need to run "saveenv" which will save **everything**.  This could be quite confusing for someone playing around with different variables, then booting normally and finding that their changes were unexpectedly saved potentially leaving them in an unbootable state.  One way of working around this would be to drop all unsaved changes to the ENV prior to running bootmenu.

Thoughts @PabloPL  or @MateuszKrawczuk ?

**Comment by MateuszKrawczuk** [comment]
I would recommend to stick with standard samsung device behaviours like:
volume-up+power - recovery
volume down+power - upload mode
home+power - menu

I manage to get some uart output from u-boot on wave2, but it is stuck on
dram initialize. Propably fota loader doesn't configure everything

**Comment by xc-racer99** [comment]
> I would recommend to stick with standard samsung device behaviours like: volume-up+power - recovery volume down+power - upload mode home+power - menu

Good to know that's standard.  Looks like we might have to do a keymask for the different variants as that won't be possible on mine as I don't have a hardware home button but have four softkeys instead.

**Comment by PabloPL** [comment]
@xc-racer99 I though exactly about the same issue.
What do You all thinks about:
- removing support for booting from 2nd partitions from mmc/sdcard (optional, but i'm not sure if it makes sense to have multi os on phone)
- add new env variable - at boot check if it exists (it could be set from u-boot console or from linux). If it exists, use it as default boot option, otherwise boot "normally"

**Comment by xc-racer99** [comment]
To be honest, I rather like having the ability to boot from partition 1 or 2.  I have a couple of SD cards with different distributions on the first and second partitions for testing.  It's quite handy as I don't have an MMC on my variant.

We could however have a "global" toggle that would switch between partition boot numbers for all partitions.

Your new env variable was exactly what I was thinking.

I'll have a look at all of this and see what I can come up with.

**Comment by PabloPL** [comment]
If we have that env variable for setting default boot option like we want - i'm happy with leaving both (1 and 2 or even adding more ;) ) partitions for sdcard/mmc.

**Comment by xc-racer99** [comment]
Implemented with https://github.com/xc-racer99/u-boot-galaxys4g/commit/1079f7b107d1c9eca0d8bcb26a9af91901093488 and https://github.com/xc-racer99/u-boot-galaxys4g/commit/86d42e8c5528b4dccc9a42a4bf01420a8876e4c4
