### ISSUE TITLE
U-boot console (inside menu generated from extlinux.conf) is not working

### ISSUE THREAD

**Issue by PabloPL** [xc-racer99/u-boot-aries#32]
When selecting u-boot console from boot menu generated from extlinux.conf, it'll start first kernel from that file, instead of starting console.

```
  *** U-Boot Boot Menu ***

   * Mainline Kernel
     Vendor Kernel
     U-Boot console
```

**Comment by xc-racer99** [comment]
Yep, thanks for opening this issue.

Another oddity that needs to be fixed with the pxelinux/bootmenu integration is that the default option isn't respected.
