### ISSUE TITLE
Booting using extlinux doesn't use append 

### ISSUE THREAD

**Issue by gipi** [xc-racer99/u-boot-aries#35]
I compiled the kernel with

```
CONFIG_CMDLINE_FROM_BOOTLOADER=y
````

and the extlinux.conf is like

```
default Yocto
label Yocto
   kernel /zImage-s5pv210-galaxys--5.2.32+git0+bb2776d6be_73b12de4c8-r0-s5pv210-20200402133134.dtb.bin
   fdtdir /
append root=/dev/mmcblk2p2 rootwait console=ttySAC2 console=tty earlyprintk
```
``u-boot`` seems to parse it correctly 

```
 ...
Scanning mmc 0:1...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
229 bytes read in 16 ms (13.7 KiB/s)
0:      Yocto
Retrieving file: /zImage-s5pv210-galaxys--5.2.32+git0+bb2776d6be_73b12de4c8-r0-s5pv210-20200402133134.dtb.bin
3800010 bytes read in 730 ms (5 MiB/s)
append: root=/dev/mmcblk2p2 rootwait rootwait console=ttySAC2 console=tty earlyprintk
Retrieving file: /s5pv210-galaxys.dtb
30586 bytes read in 21 ms (1.4 MiB/s)
Kernel image @ 0x32000000 [ 0x000000 - 0x398450 ]
## Flattened Device Tree blob at 33000000
   Booting using the fdt blob at 0x33000000
   Loading Device Tree to 34ff5000, end 34fff779 ... OK

Starting kernel ...
  ...
```

but the kernel boots with the options has been compiled with

```
root@s5pv210:~# dmesg | grep command
Kernel command line: root=/dev/mmcblk2p2 rootwait rw ramdisk=8192 console=ttySAC2,115200
```

I'm missing something obvious or is it a bug?

**Comment by kwizart** [comment]
> CONFIG_CMDLINE_FROM_BOOTLOADER=y

I don't have this config option set in my side (not even in the fedora armv7 config using extlinux's cmdline by default) and I can correctly set the cmdline from extlinux.

I think the BOOTLOADER in this config is meant for u-boot, not extlinux.

**Comment by gipi** [comment]
ok but isn't ``u-boot`` that reads ``extlinux`` and sets the ``cmdline``?

**Comment by kwizart** [comment]
I would say u-boot hands over to extlinux, then the kernel.
So at extlinux step u-boot isn't involved anymore.

**Comment by xc-racer99** [comment]
Hmm, here's whats in my .config:
```
CONFIG_CMDLINE="root=/dev/ram0 rw ramdisk=8192 initrd=0x20800000,8M console=ttySAC1,115200 init=/linuxrc"
CONFIG_CMDLINE_FROM_BOOTLOADER=y
# CONFIG_CMDLINE_EXTEND is not set
# CONFIG_CMDLINE_FORCE is not set
```
and my extlinux.conf entry looks like
```
ui menu.c32
menu autoboot Samsung Galaxy S Automatic boot in # second{,s}. Press a key for options.
menu title Samsung Galaxy S Boot Options.
timeout 0

label PostmarketOS Mainline Kernel
        kernel /vmlinuz-samsung-aries
        append ubi.mtd=ubi ${mtdparts} console=ttySAC2,115200 PMOS_NO_OUTPUT_REDIRECT
        fdtdir /
        initrd /initramfs-samsung-aries
```

It sets the cmdline as I'd expect at `ubi.mtd=ubi ${mtdparts} console=ttySAC2,115200 PMOS_NO_OUTPUT_REDIRECT` (note that the ${mtdparts} does get expanded to mtdparts=b006000...)

I'm not sure what's going on in your case.  Mind attaching the kernel and the full .config and I'll see if I can reproduce it?

**Comment by gipi** [comment]
Ok, here the [kernel](https://ktln2.org/public/zImage-s5pv210-galaxys-s5pv210.dtb.bin) and the [config](https://ktln2.org/public/defconfig)

**Comment by xc-racer99** [comment]
Ok, haven't tested this, but I think I know what's going on.
* You have CONFIG_ARM_APPENDED_DTB=y set and are appending a DTB
* This means that the kernel is reading the DTB appended and then trying to read any ATAGS from u-boot
* However, you have defined fdtdir and a DTB blob is found, u-boot is modifying the separate DTB file which the kernel isn't even using not providing any ATAGS

The best solution is to simply stop appending the DTB to the kernel and/or remove CONFIG_ARM_APPENDED_DTB=y from your defconfig.  CONFIG_ARM_APPENDED_DTB shouldn't be used except where needed because of the following (from arch/arm/Kconfig)
```
	  Beware that there is very little in terms of protection against
	  this option being confused by leftover garbage in memory that might
	  look like a DTB header after a reboot if no actual DTB is appended
	  to zImage.  Do not leave this option active in a production kernel
	  if you don't intend to always append a DTB.  Proper passing of the
	  location into r2 of a bootloader provided DTB is always preferable
	  to this option.
```

Alternatively, removing fdtdir from the extlinux.conf might work, but I'm not sure.

**Comment by gipi** [comment]
thank you, finally you solved my problem, sorry for wasting your time :)

Only one more question, to boot a system from flash what's the procedure? I imagine I need to flash with heimdall but I don't understand if I need to repartition it with like two partition: one extlinux and one for the root filesystem or simply flashing a ``uImage`` and the root filesystem in another partition? I read the wiki but it's not clear, if you have some documents that I can read would be great.

**Comment by xc-racer99** [comment]
> thank you, finally you solved my problem, sorry for wasting your time :)
> 
Hey, no problem.  Please close this issue since its fixed :)

> Only one more question, to boot a system from flash what's the procedure? I imagine I need to flash with heimdall but I don't understand if I need to repartition it with like two partition: one extlinux and one for the root filesystem or simply flashing a `uImage` and the root filesystem in another partition? I read the wiki but it's not clear, if you have some documents that I can read would be great.

Which flash are you trying to boot from - the internal flash/emmc/movinand/internal sd (/dev/mmcblk0) or from the OneNAND?  I've never booted linux from the internal storage and I've only booted Android from the OneNAND.

To boot from the internal storage, I suspect you'd have to repartition to match what works on an SD card, and frankly, the easiest way I can think of is from Linux booted on the SD Card :)  As far as u-boot is concerned, the SD card and the MMC are treated identically.  I'm not overly familiar with the internal storage as I didn't have a variant with internal storage until 6 months ago.

**Comment by gipi** [comment]
> Which flash are you trying to boot from - the internal flash/emmc/movinand/internal sd (/dev/mmcblk0) or from the OneNAND? I've never booted linux from the internal storage and I've only booted Android from the OneNAND.
> 

I want to boot from the flash and I don't know what the OneNAND is, I thought that it was another name for the internal flash.

**Comment by xc-racer99** [comment]
> I want to boot from the flash and I don't know what the OneNAND is, I thought that it was another name for the internal flash.

Nope, there's two internal storage mechanisms and they're both "flash".  The MMC is exposed as a block layer interface and is on the i9000 either 8GB or 16GB.  The OneNAND is exposed as raw flash in an MTD interface (ie has no built-in wear levelling, so needs a special filesystem such as yaffs2, jffs2, ubifs, etc) and is 512MB but is typically faster than the MMC/MoviNAND.  The bootloaders are stored on the OneNAND (the internal iROM is configured to boot from there by default) and when using heimdall you're typically writing to the OneNAND.  On stock Android on the i9000, the bootloaders, efs, kernel, recovery, system, and cache are on the OneNAND, the /data and the /sdcard partitions are on the MoviNAND IIRC.

For booting linux, you can pretty much ignore the OneNAND as the only thing that is on it that is important is u-boot and the first stage bootloader.

My variant (SGH-T959P) is slightly different and has no MMC but the OneNAND is 1GB in size (a fairly poor tradeoff, IMO).
