### ISSUE TITLE
Graphical boot menu

### ISSUE THREAD

**Issue by xc-racer99** [xc-racer99/u-boot-aries#4]
Select boot device based on volume up/down/power buttons

Built-in Samsung Tizen one no longer builds.  Options include
1) Forward porting the tizen-based code
2) Port https://forum.xda-developers.com/showthread.php?t=962708 (and make it generic?)
3) Custom solution

**Comment by xc-racer99** [comment]
Looks as if CONFIG_CMD_BOOTMENU is what we need, it's already present.

Edit: Unfortunately, need to add the buttons as keys somehow...

Edit2: board/kosagi/novena/novena.c has a simple gpio keys implementation...

**Comment by PabloPL** [comment]
Little hint:
In few places i saw something like this
```ext4load mmc 0:1 0x32000000 uImage; bootm 0x32000000```
We could extract uImage load addr (0x32000000) to variable, also the same for dtb load addr/ramdisk/etc)
and then we could just write
```ext4load mmc 0:1 {kernel_load_addr} uImage; bootm {kernel_load_addr}```
Later if we would make any changes, it would be just in one place.

**Comment by xc-racer99** [comment]
Good point, I'll do that.  The s6e63m0 branch is really quite a big hack right now...  FIMD isn't working yet and haven't managed to start writing the gpio keys driver.

**Comment by xc-racer99** [comment]
Created new branch https://github.com/xc-racer99/u-boot-galaxys4g/tree/simple-fb which uses the FB setup by the SBL and the simple-fb driver as opposed to FIMD (I couldn't get FIMD to work).  It also adds a gpio-keys driver and the bootmenu entries.

@PabloPL Would you mind testing this when you get a chance?  It's working fine here.

**Comment by PabloPL** [comment]
Thanks for great work! This is what i wanted to have on Aries (graphical boot menu).
Also thanks for options for sdcard/mmcboot - those were missing in first uboot port.

Hm..now if we could make it possible to update kernel from uboot, by not having to use uart cable.
Maybe we should overwrite parition layout for onenand and just use "usb mass storage" from uboot (and just put file by hand)?
What is Your opinion on this?

Again, great work.

Edit 1:
It looks like it should be also possible to make switch uboot console to usb.

Edit 2:
After adding something like this
```env_set("bootmenu_5", "MMC - Mass Storage=ums 0 mmc 0;");```
I was able to mount from menu all partitions from mmc and then we can easly update kernel.
Similar for sdcard.

Created PR for this. Also preparing simple patch which will allow to read uImage from fat32 partitions (so kernel update could be made also from Windows/MacOS devices).

**Comment by xc-racer99** [comment]
Support added with af07e71cd3e993216e136ad76f0132ea44fd34b1 among other commits
